project_id = "lzjpvvcwoacwactqhlvq"

[functions.improve-prompt]
verify_jwt = false

[functions.apply-all-coaching-tips]
enabled = true
verify_jwt = false

[functions.analyze-prompt]
verify_jwt = false

[functions.coach-prompt]
verify_jwt = false

[functions.apply-coaching-tip]
verify_jwt = false
